# Generated by gnosivela-gen. DO NOT EDIT.
# Source: procurement.supplier @1.2
from dataclasses import dataclass, field
from typing import List, Optional

__all__ = ["Supplier"]


@dataclass
class Supplier:
    canonicalSupplierId: str
    riskScore: Optional[float] = None
    status: Optional[str] = None
